### ISSUE TITLE
Issue installing Bazarr

### ISSUE THREAD

**Issue by bolex17** [coder8338/appbox_swizzin_installer#2]
Seems to install OK but getting the following error.

```
bazarr.service - Bazarr for appbox
    Loaded: loaded (/etc/systemd/system/bazarr.service, enabled)
    Active: active (running)
appbox@debian:/home$ sudo nano /etc/systemd/system/bazarr.service
appbox@debian:/home$ cd /opt/bazarr
appbox@debian:/opt/bazarr$ ls
bazarr	bazarr.py  bin	data  frontend	libs  requirements.txt	VERSION
appbox@debian:/opt/bazarr$ cd ~/.config
appbox@debian:~/.config$ ls
htop  log  Prowlarr  qBittorent_bak  qBittorrent  Radarr  rclone  sabnzbd  Sonarr  systemd
appbox@debian:~/.config$ sudo systemctl status bazarr
bazarr.service - Bazarr for appbox
    Loaded: loaded (/etc/systemd/system/bazarr.service, enabled)
    Active: failed (failed)
appbox@debian:~/.config$ sudo systemctl start bazarr
appbox@debian:~/.config$ sudo nano /etc/systemd/system/bazarr.service
appbox@debian:~/.config$ /opt/.venv/bazarr/bin/python3 /opt/bazarr/bazarr.py
Bazarr starting...
Traceback (most recent call last):
  File "/opt/bazarr/bazarr/../libs/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bazarr/bazarr/main.py", line 31, in <module>
    from get_series import *  # noqa E402
  File "/opt/bazarr/bazarr/get_series.py", line 12, in <module>
    from get_episodes import sync_episodes
  File "/opt/bazarr/bazarr/get_episodes.py", line 12, in <module>
    from get_subtitle.mass_download import episode_download_subtitles
  File "/opt/bazarr/bazarr/get_subtitle/__init__.py", line 3, in <module>
    from . import mass_download  # noqa: W0611
  File "/opt/bazarr/bazarr/get_subtitle/mass_download/__init__.py", line 3, in <module>
    from .movies import movies_download_subtitles  # noqa: W0611
  File "/opt/bazarr/bazarr/get_subtitle/mass_download/movies.py", line 17, in <module>
    from ..download import generate_subtitles
  File "/opt/bazarr/bazarr/get_subtitle/download.py", line 20, in <module>
    from .processing import process_subtitle
  File "/opt/bazarr/bazarr/get_subtitle/processing.py", line 10, in <module>
    from analytics import track_event
  File "/opt/bazarr/bazarr/analytics.py", line 17, in <module>
    sonarr_version = get_sonarr_info.version()
  File "/opt/bazarr/bazarr/utils.py", line 262, in version
    sonarr_version = requests.get(sv, timeout=60, verify=False, headers=headers).json()['version']
  File "/opt/bazarr/bazarr/../libs/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-capable" content="yes" />

    <!-- Chrome, Opera, and Firefox OS -->
    <meta name="theme-color" content="#3a3f51" />
    <!-- Windows Phone -->
    <meta name="msapplication-navbutton-color" content="#3a3f51" />

    <meta name="description" content="Sonarr" />

    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="/sonarr/Content/Images/Icons/apple-touch-icon.png?h=d+iS4xWxn2A2bjUwrERmSg"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="/sonarr/Content/Images/Icons/favicon-32x32.png?h=s64FHSxrh1sgZCiBBIVikQ"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="/sonarr/Content/Images/Icons/favicon-16x16.png?h=wksVbPqhKGB2B5P0O0h8IQ"
    />
    <link rel="manifest" href="/sonarr/Content/Images/Icons/manifest.json?h=DmoSjQqByGr1aINOqvSg9w" crossorigin="use-credentials" />
    <link
      rel="mask-icon"
      href="/sonarr/Content/Images/Icons/safari-pinned-tab.svg?h=LLFuxx74TMIn3Vx2ai6a1A"
      color="#00ccff"
    />
    <link
      rel="shortcut icon"
      type="image/ico"
      href="/sonarr/favicon.ico?h=ZX67/60OXHGhAQ+8myebHg"
      data-no-hash
    />
    <meta
      name="msapplication-config"
      content="/Content/Images/Icons/browserconfig.xml"
    />

    <link rel="stylesheet" type="text/css" href="/sonarr/Content/styles.css?h=sbxPVdW+yWbVRS941PK8Nw" />
    <link rel="stylesheet" type="text/css" href="/sonarr/Content/Fonts/fonts.css?h=mBv1x1/yHnvphLclzeQIBA" />

    <title>Login - Sonarr</title>

    <style>
      body {
        background-color: #f5f7fa;
        color: #656565;
        font-family: "Roboto", "open sans", "Helvetica Neue", Helvetica, Arial,
          sans-serif;
      }

      .center {
        display: flex;
        justify-content: center;
      }

      .content {
        flex: 0 0 325px;
      }

      .logo {
        width: 32px;
        height: 32px;
      }

      .panel {
        margin-top: 50px;
        border-radius: 4px;
      }

      .panel-header {
        display: flex;
        justify-content: center;
        padding: 10px;
        border-top-left-radius: 4px;
        border-top-right-radius: 4px;
        background-color: #3a3f51;
      }

      .panel-body {
        padding: 20px;
        border-bottom-right-radius: 4px;
        border-bottom-left-radius: 4px;
        background-color: #fff;
      }

      .sign-in {
        padding: 10px 0;
        text-align: center;
      }

      .form-group {
        margin: 20px 0;
      }

      .form-input {
        box-sizing: border-box;
        padding: 6px 16px;
        width: 100%;
        height: 35px;
        border: 1px solid #dde6e9;
        border-radius: 4px;
        box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
      }

      .form-input:focus {
        outline: 0;
        border-color: #66afe9;
        box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075),
          0 0 8px rgba(102, 175, 233, 0.6);
      }

      .button {
        overflow: hidden;
        margin-top: 20px;
        padding: 10px 0;
        width: 100%;
        border: 1px solid;
        border-color: #5899eb;
        border-radius: 4px;
        background-color: #5d9cec;
        color: #fff;
        vertical-align: middle;
        text-align: center;
        white-space: nowrap;
        line-height: normal;
      }

      .button:hover {
        border-color: #3483e7;
        background-color: #4b91ea;
        color: #fff;
        text-decoration: none;
      }

      .copy {
        margin-top: 15px;
        text-align: center;
        font-size: 14px;
      }

      .remember-me-container {
        display: flex;
        justify-content: space-between;
        line-height: 25px;
      }

      .remember-me {
        font-size: 14px;
      }

      .forgot-password {
        margin-left: auto;
        color: #909fa7;
        text-decoration: none;
        font-size: 13px;
      }

      .forgot-password:focus,
      .forgot-password:hover {
        color: #748690;
        text-decoration: underline;
      }

      .forgot-password:visited {
        color: #748690;
      }

      .login-failed {
        margin-top: 20px;
        color: #f05050;
        font-size: 14px;
      }

      .hidden {
        display: none;
      }

      @media only screen and (min-device-width: 375px) and (max-device-width: 812px) {
        .form-input {
          font-size: 16px;
        }
      }
    </style>
  </head>

  <body>
    <div class="center">
      <div class="content">
        <div class="panel">
          <div class="panel-header">
            <img src="/sonarr/Content/Images/logo.svg?h=lzId6hpOgICvOf7RS90NNQ" alt="Image" class="logo" />
          </div>

          <div class="panel-body">
            <div class="sign-in">
              SIGN IN TO CONTINUE
            </div>

            <form
              role="form"
              data-parsley-validate=""
              novalidate=""
              class="mb-lg"
              method="POST"
            >
              <div class="form-group">
                <input
                  type="email"
                  name="username"
                  class="form-input"
                  placeholder="Username"
                  autocomplete="off"
                  pattern=".{1,}"
                  required
                  title="User name is required"
                  autoFocus="true"
                  autoCapitalize="false"
                />
              </div>

              <div class="form-group">
                <input
                  type="password"
                  name="password"
                  class="form-input"
                  placeholder="Password"
                  required
                />
              </div>

              <div class="remember-me-container">
                <span class="remember-me">
                  <input
                    type="checkbox"
                    name="rememberMe"
                    id="rememberMe"
                    checked="checked"
                  />
                  <label for="rememberMe">Remember Me</label>
                </span>

                <a
                  href="https://wiki.servarr.com/Sonarr_FAQ#Help_I_have_forgotten_my_password"
                  class="forgot-password"
                  >Forgot your password?</a
                >
              </div>
              <button type="submit" class="button">Login</button>

              <div id="login-failed" class="login-failed hidden">
                Incorrect Username or Password
              </div>
            </form>
          </div>
        </div>

        <div id="copy" class="copy hidden">
          <span>&copy;</span>
          <span id="year"></span>
          <span>-</span>
          <span>Sonarr</span>
        </div>
      </div>
    </div>
  </body>

  <script type="text/javascript">
    var yearSpan = document.getElementById("year");
    yearSpan.innerHTML = "2010-" + new Date().getFullYear();

    var copyDiv = document.getElementById("copy");
    copyDiv.classList.remove("hidden");

    if (window.location.search.indexOf("loginFailed=true") > -1) {
      var loginFailedDiv = document.getElementById("login-failed");

      loginFailedDiv.classList.remove("hidden");
    }
  </script>
</html>
: 0
Bazarr exited.
```

**Comment by coder8338** [comment]
What's in the logs in `/var/log/journal/bazarr.log`?

I think that's what the logs are called otherwise just check in `/var/log` for the correct log file.

**Comment by bolex17** [comment]
Please see attached log files.

[bazarr.service.log](https://github.com/coder8338/appbox_swizzin_installer/files/8518410/bazarr.service.log)

**Comment by coder8338** [comment]
Looks like it might be related to https://github.com/morpheus65535/bazarr/issues/1518

Can you please open an issue here: https://github.com/morpheus65535/bazarr/issues
